FROM node:18-alpine AS base

WORKDIR /app
COPY package.json .
COPY package-lock.json .

FROM base AS dependencies
RUN npm install

FROM base AS runtime
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .
CMD ["npx","ponder","dev"]
