services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: nounberg
      POSTGRES_PASSWORD: nounberg
      POSTGRES_DB: nounberg
    ports:
      - "5432:5432"
    volumes:
      - nounberg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nounberg || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis-data:/data

  memcached:
    image: memcached:1.6-alpine
    ports:
      - "11211:11211"
    command: memcached -m 128

volumes:
  nounberg-data:
    name: nounberg-data-dev
  redis-data:
    name: redis-data-dev