FROM node:18-alpine AS base

WORKDIR /app
COPY package*.json .

FROM base AS dependencies
RUN npm install

FROM alpine:latest AS filter
WORKDIR /filter
COPY . .
RUN rm -rf src/workers

FROM base AS runtime
WORKDIR /app
COPY --from=dependencies /app/node_modules ./node_modules
COPY --from=filter /filter .

CMD ["npx", "ponder", "start", "--log-format", "json"]