services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    environment:
      ANVIL_IP_ADDR: "0.0.0.0"
      working_dir: /anvil
    ports:
      - "8545:8545"
    command: anvil --host 0.0.0.0 --port 8545 --block-time 1 --accounts 10 --balance 10000

networks:
  default:
    name: ponder-test
